---
deployment:
  tasks:
    - export DEPLOYPATH=/home/republ23/public_html/pkbm_public/
    - /bin/cp -R ./public/Assets/* $DEPLOYPATH/Assets
    - /bin/cp -R ./public/css/* $DEPLOYPATH/css
    - /bin/cp -R ./public/js/* $DEPLOYPATH/js
