---
deployment:
  tasks:
    - export DEPLOYPATH=/home/republ23/public_html/test
    - /bin/cp ./public/Assets/* $DEPLOYPATH/Assets
    - /bin/cp ./public/css/* $DEPLOYPATH/css
    - /bin/cp ./public/js/* $DEPLOYPATH/js
